// Phrase bank with themes and hints
export const PHRASES = [
  { phrase: "FLIMSY FOREVER", theme: "Contradictions", hint: "Weak but eternal" },
  { phrase: "FUZZY LOGIC", theme: "Technology", hint: "Unclear reasoning in computing" },
  { phrase: "QUICK BROWN FOX", theme: "Classic Phrases", hint: "Famous typing exercise" },
  { phrase: "JAZZ MUSIC VIBES", theme: "Entertainment", hint: "Smooth improvisational feeling" },
  { phrase: "PIXEL PERFECT", theme: "Design", hint: "Flawless digital precision" },
  { phrase: "COSMIC ENERGY", theme: "Space & Nature", hint: "Universal force from the stars" },
  { phrase: "WINTER WONDERLAND", theme: "Seasons", hint: "Magical snowy scene" },
  { phrase: "GOLDEN SUNSET", theme: "Nature", hint: "Yellow-orange sky at dusk" },
  { phrase: "BRAVE NEW WORLD", theme: "Literature", hint: "Huxley's dystopian novel" },
  { phrase: "ELECTRIC DREAMS", theme: "Technology", hint: "Powered visions of the future" },
  { phrase: "PAPER AIRPLANE", theme: "Everyday Objects", hint: "Folded flying toy" },
  { phrase: "SILVER LINING", theme: "Idioms", hint: "Hope in a bad situation" },
  { phrase: "RUBBER DUCKY", theme: "Everyday Objects", hint: "Yellow bath toy" },
  { phrase: "NEON LIGHTS", theme: "Urban Life", hint: "Bright glowing city signs" },
  { phrase: "CRYSTAL CLEAR", theme: "Idioms", hint: "Perfectly transparent or obvious" },

  // Food & Cooking
  { phrase: "CHOCOLATE CHIP COOKIE", theme: "Food & Cooking", hint: "Sweet baked treat with morsels" },
  { phrase: "FRESH SQUEEZED JUICE", theme: "Food & Cooking", hint: "Citrus drink made by hand" },
  { phrase: "GRILLED CHEESE SANDWICH", theme: "Food & Cooking", hint: "Hot toasted bread with melted dairy" },
  { phrase: "MAPLE SYRUP", theme: "Food & Cooking", hint: "Sweet tree sap for pancakes" },
  { phrase: "SPICY CHICKEN WINGS", theme: "Food & Cooking", hint: "Hot sauced poultry appetizer" },
  { phrase: "BUTTER POPCORN", theme: "Food & Cooking", hint: "Movie theater snack" },
  { phrase: "STRAWBERRY SMOOTHIE", theme: "Food & Cooking", hint: "Blended berry drink" },
  { phrase: "DOUBLE BACON CHEESEBURGER", theme: "Food & Cooking", hint: "Extra meat and cheese sandwich" },
  { phrase: "VANILLA ICE CREAM", theme: "Food & Cooking", hint: "Classic frozen dessert flavor" },
  { phrase: "PEPPERONI PIZZA", theme: "Food & Cooking", hint: "Italian pie with spicy meat" },

  // Sports & Games
  { phrase: "SLAM DUNK CHAMPION", theme: "Sports & Games", hint: "Basketball aerial master" },
  { phrase: "CHESS GRANDMASTER", theme: "Sports & Games", hint: "Top ranked board game player" },
  { phrase: "HOLE IN ONE", theme: "Sports & Games", hint: "Perfect golf shot" },
  { phrase: "TOUCHDOWN CELEBRATION", theme: "Sports & Games", hint: "Football scoring dance" },
  { phrase: "POKER FACE", theme: "Sports & Games", hint: "Emotionless card game expression" },
  { phrase: "HOME RUN DERBY", theme: "Sports & Games", hint: "Baseball power hitting contest" },
  { phrase: "CHECKERED FLAG", theme: "Sports & Games", hint: "Racing finish signal" },
  { phrase: "PENALTY KICK", theme: "Sports & Games", hint: "Soccer free shot at goal" },
  { phrase: "BOWLING STRIKE", theme: "Sports & Games", hint: "Knocking down all pins" },
  { phrase: "TRIPLE WORD SCORE", theme: "Sports & Games", hint: "Scrabble bonus space" },

  // Movies & TV
  { phrase: "COMING ATTRACTIONS", theme: "Movies & TV", hint: "Theater previews" },
  { phrase: "BINGE WATCHING", theme: "Movies & TV", hint: "Viewing many episodes straight" },
  { phrase: "PLOT TWIST ENDING", theme: "Movies & TV", hint: "Surprising story conclusion" },
  { phrase: "OPENING CREDITS", theme: "Movies & TV", hint: "Start of show titles" },
  { phrase: "LAUGH TRACK", theme: "Movies & TV", hint: "Recorded sitcom chuckles" },
  { phrase: "CLIFFHANGER FINALE", theme: "Movies & TV", hint: "Suspenseful season ending" },
  { phrase: "STREAMING SERVICE", theme: "Movies & TV", hint: "Online video platform" },
  { phrase: "DIRECTOR CUT", theme: "Movies & TV", hint: "Filmmaker's preferred version" },
  { phrase: "SPECIAL EFFECTS", theme: "Movies & TV", hint: "Movie visual wizardry" },
  { phrase: "STANDING OVATION", theme: "Movies & TV", hint: "Audience rises to applaud" },

  // Music
  { phrase: "GUITAR SOLO", theme: "Music", hint: "String instrument spotlight moment" },
  { phrase: "DRUM ROLL PLEASE", theme: "Music", hint: "Percussion buildup request" },
  { phrase: "GREATEST HITS ALBUM", theme: "Music", hint: "Collection of popular songs" },
  { phrase: "MUSIC VIDEO", theme: "Music", hint: "Visual accompaniment to song" },
  { phrase: "VINYL RECORD", theme: "Music", hint: "Classic grooved disc format" },
  { phrase: "SINGING IN HARMONY", theme: "Music", hint: "Voices blending together" },
  { phrase: "CONCERT TOUR", theme: "Music", hint: "Series of live performances" },
  { phrase: "BASS DROP", theme: "Music", hint: "Electronic music low frequency moment" },
  { phrase: "CATCHY CHORUS", theme: "Music", hint: "Memorable repeated song part" },
  { phrase: "ACOUSTIC VERSION", theme: "Music", hint: "Unplugged song arrangement" },

  // Nature & Weather
  { phrase: "RAINBOW AFTER RAIN", theme: "Nature & Weather", hint: "Colorful arc following storm" },
  { phrase: "THUNDER AND LIGHTNING", theme: "Nature & Weather", hint: "Storm sound and flash" },
  { phrase: "AUTUMN LEAVES FALLING", theme: "Nature & Weather", hint: "Trees shedding in fall" },
  { phrase: "OCEAN BREEZE", theme: "Nature & Weather", hint: "Coastal wind" },
  { phrase: "MOUNTAIN PEAK", theme: "Nature & Weather", hint: "Highest point of elevation" },
  { phrase: "FOGGY MORNING", theme: "Nature & Weather", hint: "Misty dawn" },
  { phrase: "DESERT MIRAGE", theme: "Nature & Weather", hint: "Hot sand optical illusion" },
  { phrase: "BLOOMING FLOWERS", theme: "Nature & Weather", hint: "Plants opening up" },
  { phrase: "CRASHING WAVES", theme: "Nature & Weather", hint: "Surf hitting shore" },
  { phrase: "SHOOTING STAR", theme: "Nature & Weather", hint: "Meteor streak in sky" },

  // Technology & Science
  { phrase: "QUANTUM PHYSICS", theme: "Technology & Science", hint: "Subatomic particle study" },
  { phrase: "ARTIFICIAL INTELLIGENCE", theme: "Technology & Science", hint: "Machine learning systems" },
  { phrase: "SMARTPHONE BATTERY", theme: "Technology & Science", hint: "Mobile device power source" },
  { phrase: "VIRTUAL REALITY", theme: "Technology & Science", hint: "Computer simulated environment" },
  { phrase: "SOLAR PANEL", theme: "Technology & Science", hint: "Sun energy collector" },
  { phrase: "DNA SEQUENCE", theme: "Technology & Science", hint: "Genetic code order" },
  { phrase: "ROCKET LAUNCH", theme: "Technology & Science", hint: "Spacecraft takeoff" },
  { phrase: "WIRELESS CHARGING", theme: "Technology & Science", hint: "Cordless power transfer" },
  { phrase: "CLOUD COMPUTING", theme: "Technology & Science", hint: "Internet based data storage" },
  { phrase: "LASER BEAM", theme: "Technology & Science", hint: "Focused light ray" },

  // Travel & Places
  { phrase: "TROPICAL PARADISE", theme: "Travel & Places", hint: "Warm island getaway" },
  { phrase: "EIFFEL TOWER", theme: "Travel & Places", hint: "Paris landmark" },
  { phrase: "ROAD TRIP ADVENTURE", theme: "Travel & Places", hint: "Car journey exploration" },
  { phrase: "SANDY BEACH", theme: "Travel & Places", hint: "Coastal shore" },
  { phrase: "CITY SKYLINE", theme: "Travel & Places", hint: "Urban building silhouette" },
  { phrase: "CAMPING UNDER STARS", theme: "Travel & Places", hint: "Outdoor overnight with night sky" },
  { phrase: "AIRPORT TERMINAL", theme: "Travel & Places", hint: "Flight departure building" },
  { phrase: "MOUNTAIN CABIN", theme: "Travel & Places", hint: "Remote hillside dwelling" },
  { phrase: "SUBWAY STATION", theme: "Travel & Places", hint: "Underground train stop" },
  { phrase: "CRUISE SHIP", theme: "Travel & Places", hint: "Large ocean vacation vessel" },

  // Animals
  { phrase: "PUPPY DOG EYES", theme: "Animals", hint: "Canine pleading look" },
  { phrase: "BUTTERFLY WINGS", theme: "Animals", hint: "Colorful insect appendages" },
  { phrase: "BUSY BEAVER", theme: "Animals", hint: "Hardworking dam builder" },
  { phrase: "SLEEPING LION", theme: "Animals", hint: "Resting jungle king" },
  { phrase: "WISE OLD OWL", theme: "Animals", hint: "Smart nocturnal bird" },
  { phrase: "SWIMMING DOLPHIN", theme: "Animals", hint: "Aquatic mammal gliding" },
  { phrase: "HOPPING KANGAROO", theme: "Animals", hint: "Australian bouncing marsupial" },
  { phrase: "PROWLING TIGER", theme: "Animals", hint: "Striped cat stalking" },
  { phrase: "GALLOPING HORSE", theme: "Animals", hint: "Fast running equine" },
  { phrase: "SLITHERING SNAKE", theme: "Animals", hint: "Limbless reptile moving" },

  // Emotions & Feelings
  { phrase: "HAPPY BIRTHDAY SURPRISE", theme: "Emotions & Feelings", hint: "Unexpected celebration moment" },
  { phrase: "NERVOUS ENERGY", theme: "Emotions & Feelings", hint: "Anxious restlessness" },
  { phrase: "PURE JOY", theme: "Emotions & Feelings", hint: "Complete happiness" },
  { phrase: "QUIET CONFIDENCE", theme: "Emotions & Feelings", hint: "Calm self assurance" },
  { phrase: "MIXED EMOTIONS", theme: "Emotions & Feelings", hint: "Conflicting feelings" },
  { phrase: "OVERWHELMING GRATITUDE", theme: "Emotions & Feelings", hint: "Intense thankfulness" },
  { phrase: "PEACEFUL MOMENT", theme: "Emotions & Feelings", hint: "Calm serene time" },
  { phrase: "BURNING PASSION", theme: "Emotions & Feelings", hint: "Intense enthusiasm" },
  { phrase: "BITTERSWEET GOODBYE", theme: "Emotions & Feelings", hint: "Happy sad farewell" },
  { phrase: "FIRST LOVE", theme: "Emotions & Feelings", hint: "Initial romantic connection" },

  // Idioms & Expressions
  { phrase: "BREAK THE ICE", theme: "Idioms & Expressions", hint: "Start conversation" },
  { phrase: "ONCE IN A BLUE MOON", theme: "Idioms & Expressions", hint: "Very rarely happens" },
  { phrase: "PIECE OF CAKE", theme: "Idioms & Expressions", hint: "Very easy task" },
  { phrase: "BEATING AROUND THE BUSH", theme: "Idioms & Expressions", hint: "Avoiding the point" },
  { phrase: "JUMP THE GUN", theme: "Idioms & Expressions", hint: "Start too early" },
  { phrase: "RAIN CATS AND DOGS", theme: "Idioms & Expressions", hint: "Heavy downpour" },
  { phrase: "HIT THE NAIL ON HEAD", theme: "Idioms & Expressions", hint: "Exactly correct" },
  { phrase: "BLESSING IN DISGUISE", theme: "Idioms & Expressions", hint: "Hidden good fortune" },
  { phrase: "SPILL THE BEANS", theme: "Idioms & Expressions", hint: "Reveal secret" },
  { phrase: "BACK TO SQUARE ONE", theme: "Idioms & Expressions", hint: "Starting over completely" },

  // Famous Movie Quotes
  { phrase: "MAY THE FORCE BE WITH YOU", theme: "Famous Movie Quotes", hint: "Star Wars blessing" },
  { phrase: "I WILL BE BACK", theme: "Famous Movie Quotes", hint: "Terminator promise" },
  { phrase: "SHOW ME THE MONEY", theme: "Famous Movie Quotes", hint: "Jerry Maguire demand" },
  { phrase: "YOU TALKING TO ME", theme: "Famous Movie Quotes", hint: "Taxi Driver challenge" },
  { phrase: "LIFE IS LIKE A BOX OF CHOCOLATES", theme: "Famous Movie Quotes", hint: "Forrest Gump wisdom" },
  { phrase: "KEEP YOUR FRIENDS CLOSE", theme: "Famous Movie Quotes", hint: "Godfather strategy advice" },
  { phrase: "THERE IS NO PLACE LIKE HOME", theme: "Famous Movie Quotes", hint: "Dorothy clicks heels" },
  { phrase: "TO INFINITY AND BEYOND", theme: "Famous Movie Quotes", hint: "Buzz Lightyear catchphrase" },
  { phrase: "YOU CANNOT HANDLE THE TRUTH", theme: "Famous Movie Quotes", hint: "Few Good Men courtroom" },
  { phrase: "HOUSTON WE HAVE A PROBLEM", theme: "Famous Movie Quotes", hint: "Apollo mission emergency" },
  { phrase: "I SEE DEAD PEOPLE", theme: "Famous Movie Quotes", hint: "Sixth Sense revelation" },
  { phrase: "JUST KEEP SWIMMING", theme: "Famous Movie Quotes", hint: "Finding Nemo encouragement" },
  { phrase: "WHY SO SERIOUS", theme: "Famous Movie Quotes", hint: "Dark Knight Joker taunt" },
  { phrase: "FRANKLY MY DEAR I DO NOT CARE", theme: "Famous Movie Quotes", hint: "Gone With Wind exit" },
  { phrase: "YOU HAD ME AT HELLO", theme: "Famous Movie Quotes", hint: "Jerry Maguire romance" },
  { phrase: "I AM YOUR FATHER", theme: "Famous Movie Quotes", hint: "Empire Strikes Back reveal" },
  { phrase: "GONNA MAKE HIM AN OFFER", theme: "Famous Movie Quotes", hint: "Godfather persuasion method" },
  { phrase: "HERE IS LOOKING AT YOU KID", theme: "Famous Movie Quotes", hint: "Casablanca toast" },
  { phrase: "YOU SHALL NOT PASS", theme: "Famous Movie Quotes", hint: "Gandalf stands firm" },
  { phrase: "NOBODY PUTS BABY IN A CORNER", theme: "Famous Movie Quotes", hint: "Dirty Dancing declaration" }
];
